version: "3.9"

services:
  bot:
    build: ./
    restart: always
    environment:
      - TZ=Asia/Seoul
  db:
    image: mongo
    restart: always
    volumes:
      - dbdata:/data/db

volume:
  dbdata:
