version: "3.9"

services:
  bot:
    build: ./
    networks:
      - default
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Seoul
  db:
    image: mongo:4.4.18
    networks:
      - default
    privileged: true
    restart: always
    volumes:
      - ./dbdata:/data/db

networks:
  default:
