version: "3.9"

services:
  bot:
    container_name: kua_bot
    build: ./
    networks:
      - kua
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Seoul
  db:
    container_name: kua_db
    image: mongo:4.4.18
    networks:
      - kua
    privileged: true
    restart: always
    volumes:
      - ./dbdata:/data/db

networks:
  kua:
